# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feature*" ]
  pull_request:
    branches: [ "main", "feature*" ]
    types: [opened, synchronize, closed]
  pull_request_review:
    branches: [ "main", "feature*" ]
    types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug context (only prints if runner debug is enabled)
      - name: Debug context
        if: ${{ runner.debug == '1' }}
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"
          echo "sha=${{ github.sha }}"
          echo "actor=${{ github.actor }}"
          echo "action=${{ github.event.action }}"
          echo "base_ref=${{ github.base_ref }}"
          echo "head_ref=${{ github.head_ref }}"
          echo "pr_number=${{ github.event.pull_request.number || '' }}"

      # --- Pushes ---
      - name: Push to main
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') }}
        run: echo "Push to main by ${{ github.actor }} (sha ${{ github.sha }})"

      - name: Push to feature*
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') }}
        run: echo "Push to feature branch '${{ github.ref_name }}' by ${{ github.actor }} (sha ${{ github.sha }})"
          
